# Generated by Django 5.1.5 on 2025-02-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('realizando', 'Realizando'), ('concluida', 'Concluída')], max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
